name: Usando Composite Action
on:
  issues:
    types: [opened,reopened]
  pull_request:
    types: [opened]

jobs:
  usando-action:
    name: Executando Composite Action
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Adicionando comentário
        uses: JvictorMarques/docker-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number }}
          comment: Teste
          GITHUB_REPOSITORY: ${{ github.repository }}